main:
  components_repository: "https://github.com/KenzyAggour/MLOPS-ML-Pipeline-for-Rental-Prices-#components"
  project_name: nyc_airbnb
  experiment_name: development
  steps: all

etl:
  sample: "sample1.csv"
  min_price: 10  # dollars
  max_price: 350  # dollars

data_check:
  kl_threshold: 0.2

modeling:
  test_size: 0.2
  val_size: 0.2
  random_seed: 42
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 15 #${modeling.max_tfidf_features}  # Placeholder for varying this parameter
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 4
    min_samples_leaf: 3
    n_jobs: -1
    criterion: mae
    max_features: 0.5 #${modeling.max_features}  # Placeholder for varying this parameter
    oob_score: true
